### ISSUE TITLE
Name or service not known

### ISSUE THREAD

**Issue by vagabond222** [TheDrHax/rpi-fan-control#2]
When installing line:
wget -O- http://local.thedrhax.us.to/apt/TheDrHax.key | sudo apt-key add -
I get following error:
--2017-08-14 18:20:17--  http://local.thedrhax.us.to/apt/TheDrHax.key
Resolving local.thedrhax.us.to (local.thedrhax.us.to)... failed: Name or service not known.
wget: unable to resolve host address ‘local.thedrhax.us.to’
gpg: no valid OpenPGP data found.

**Comment by TheDrHax** [comment]
Sorry, this repository does not longer exist. You still can build this package from source code.

Also I have just uploaded the latest release [here](https://github.com/TheDrHax/rpi-fan-control/releases/tag/2.0.0).
